### ISSUE TITLE
`freesasa` results are not used

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/prodigy-cryst#9]
While doing #7 I noticed that freesasa executed but its result is set as `cmplx_sasa` is not used anywhere:

https://github.com/haddocking/prodigy-cryst/blob/feb60e81bf9c5d995875e84058477467477e7d54/interface_classifier.py#L114

Is this some artifact of the development or is it a bug?

**Comment by katarinaelez** [comment]
Properties of the non-interacting surface (ANIS, CNIS and PNIS) require freesasa. Those features were tested at the early stages but did not make it to the final version of the predictor. So freesasa is not needed in the current version of the predictor and can be removed.

**Comment by amjjbonvin** [comment]
But they are used in the regular prodigy code!  

So if you intend to merge all three versions into one in the future you will need it (but should be part of the default version already)

**Comment by rvhonorato** [comment]
good point, noted!

**Comment by rvhonorato** [comment]
removed unused code in #7
